### ISSUE TITLE
Fatal error initializing plugin

### ISSUE THREAD

**Issue by BorzdeG** [JetBrains/intellij-stats-collector#22] opened 2018-12-22 15:46 UTC
IntelliJ IDEA 2018.3.3 Preview  Build #IU-183.5153.4

```
ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.intellij.stats.completion 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.intellij.stats.completion
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:215)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.intellij.stats.completion
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:253)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:390)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	... 16 more
Caused by: com.intellij.diagnostic.PluginException: com.jetbrains.completion.feature.FeatureManager PluginClassLoader[com.intellij.stats.completion, 183.4886.3] com.intellij.ide.plugins.cl.PluginClassLoader@6e90606d [Plugin: com.intellij.stats.completion]
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.jetbrains.completion.feature.FeatureManager PluginClassLoader[com.intellij.stats.completion, 183.4886.3] com.intellij.ide.plugins.cl.PluginClassLoader@6e90606d
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:371)
	... 20 more
2018-12-22 18:41:51,026 [   2282]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.3.3 Preview  Build #IU-183.5153.4 
2018-12-22 18:41:51,026 [   2282]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2018-12-22 18:41:51,026 [   2282]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2018-12-22 18:41:56,924 [   8180]  ERROR - llij.ide.plugins.PluginManager - Fatal error initializing 'com.intellij.openapi.keymap.KeymapManager' 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.keymap.KeymapManager'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:256)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:504)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:153)
	at com.intellij.openapi.keymap.KeymapManager.getInstance(KeymapManager.java:26)
	at com.intellij.ide.IdeEventQueue.getShortcutsShowingPopups(IdeEventQueue.java:1257)
	at com.intellij.ide.IdeEventQueue.doPostEvent(IdeEventQueue.java:1133)
	at com.intellij.ide.IdeEventQueue.postEvent(IdeEventQueue.java:1010)
	at sun.awt.PostEventQueue.flush(SunToolkit.java:2180)
	at sun.awt.SunToolkit.flushPendingEvents(SunToolkit.java:543)
	at java.awt.EventQueue.getNextEvent(EventQueue.java:552)
	at com.intellij.ide.IdeEventQueue.getNextEvent(IdeEventQueue.java:455)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:170)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at com.intellij.idea.Main.showMessage(Main.java:175)
	at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:136)
	at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:476)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.picocontainer.defaults.UnsatisfiableDependenciesException: com.intellij.openapi.keymap.impl.KeymapManagerImpl has unsatisfied dependency: class com.intellij.openapi.keymap.impl.DefaultKeymap among unsatisfiable dependencies: [[class com.intellij.openapi.keymap.impl.DefaultKeymap, class com.intellij.openapi.options.SchemeManagerFactory]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(CachingConstructorInjectionComponentAdapter.java:166)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:74)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:462)
	... 31 more
2018-12-22 18:41:56,924 [   8180]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.3.3 Preview  Build #IU-183.5153.4 
2018-12-22 18:41:56,924 [   8180]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2018-12-22 18:41:56,924 [   8180]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
```

**Comment by IRus** [comment] 2019-01-12 20:45
Possible duplicate of #20

**Closed as completed** 2019-01-22 11:39 UTC

**Comment by IRus** [comment] 2019-01-22 11:42
![image](https://user-images.githubusercontent.com/493656/51533425-ec794480-1e53-11e9-976e-4c3acd9b229a.png)

Actually there are is bad version again: @bibaev

**Comment by BorzdeG** [comment] 2019-01-22 11:45
#23

**Comment by bibaev** [comment] 2019-01-29 17:35
@IRus Thanks for your answers in the last issues.
